language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install redis-server
  - sudo service redis-server start
  - redis-server --version
  - which redis-server

install:
  - "pip install ."
  - "pip install hiredis"

script: ./tests.py

env:
  matrix:
  - "REDIS_PORT=6379"
  - "START_REDIS_SERVER=True REDIS_PORT=0 REDIS_HOST=/tmp/asyncio"
